var Student=[
    {
        name:"Karan",
        city:"Jalandhar",
        gender:"Male",
        department:"cse"
    },
    {
        name:"Harsh",
        city:"Jalandhar",
        gender:"Male",
        department:"cse"
    },
    {
        name:"Harman",
        city:"Jalandhar",
        gender:"Male",
        department:"ece"
    },
    {
        name:"Singh",
        city:"Hoshiarpur",
        gender:"Female",
        department:"AIML"
    },
    {
        name:"Manhas",
        city:"Ludhiana",
        gender:"Male",
        department:"cse"
    },
    {
        name:"chaitnya",
        city:"Jalandhar",
        gender:"Male",
        department:"cse"
    }
   
]
module.exports=Student